### ISSUE TITLE
Support <select> for cc-exp-* directives

### ISSUE THREAD

**Issue by ulion** [bendrucker/angular-credit-cards#87] opened 2015-11-29 13:08 UTC
```<select name="ccExpireYear" ng-model="ccExpireYear" ng-options="n for n in Range(currentYear, currentYear+30)" cc-exp-year full-year required></select>```

if ccExpireYear is value 2016, the 2016 is not selected when the view loaded. Range function return array of number in the specific range.

**Comment by bendrucker** [comment] 2015-11-29 15:12
Need a reproducible example to look further here

**Comment by ulion** [comment] 2015-11-30 00:10
```
<select name="ccExpireYear" ng-model="ccExpireYear" ng-options="n for n in [2015,2016,2017,2018,2019,2020]" cc-exp-year full-year required></select>
```

and set the $scope.ccExpireYear to any value between 2015-2020 in the controller, you will find that it does not select the year correctly.

**Comment by bendrucker** [comment] 2015-11-30 00:19
Thanks, but will need something I can click and see running immediately. Not doing much Angular these days so I don't have a scratch project I can easily drop this into.

**Comment by ulion** [comment] 2015-11-30 10:27
Here is a click and see example: http://codepen.io/anon/pen/MaNOQv

In the "First Controller"

2015-11-30 8:19 GMT+08:00 Ben Drucker <notifications@github.com>:

> Thanks, but will need something I can click and see running immediately.
> Not doing much Angular these days so I don't have a scratch project I can
> easily drop this into.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bendrucker/angular-credit-cards/issues/87#issuecomment-160485725>
> .
>



-- 
Ulion

**Comment by bendrucker** [comment] 2015-11-30 14:55
After thinking about it a bit more, quite a bit about the `<select>` approach wouldn't work. The library just isn't written with them in mind—`<input>` is the focus. I think it's reasonable to detect the element and handle things accordingly, but it's not something I'll be able to work on immediately. Would be happy to review a PR.

**Comment by bendrucker** [comment] 2016-02-08 16:22
Closing since this isn't something I plan to support in the library. I end up putting energy into the things I use and always choose a text input for card expiration over selects. If this is something you really want the best approach would be to write your own directive using the underlying [creditcards](npmjs.org/package/creditcards) library.

**Closed by bendrucker** 2016-02-08 16:22 UTC

**Comment by ulion** [comment] 2016-02-09 23:51
After dig, I think the key part is this:
```
ngModel.$formatters.unshift(function formatExpYear (value) {
          return value ? year.format(value, !fullYear) : ''
        })
```
the select input indeed expect number in my test case, but the format function give it string.

so the fix would be not complex, just keep the type of value, then everything will work.
```
ngModel.$formatters.unshift(function formatExpYear (value) {
          if (value) {
            var isNum = typeof value == 'number';
            value = year.format(value, !fullYear);
            if (value && isNum)
              value = +value;
          }
          return value;
        })
```

so we just keep the input value type, then we will work with any input/select field.
