### ISSUE TITLE
Form property is not set to $dirty until the user has entered a valid credit card number

### ISSUE THREAD

**Issue by owlyowl** [bendrucker/angular-credit-cards#19] opened 2015-02-19 02:36 UTC
If the user enters bad input and/or the tabs off the credit card field the $dirty flag is not set on the form object.

i.e. formname.field name.$dirty is not set to true until a valid input has been received.

Can be reproduced by using the try it page: http://embed.plnkr.co/uE47aZ/preview and entering in anything like 4242 and tabbing off.

Can there be an option to allow invalid input to cause the form side of things to update?

```
<input type="text" class="input-text" id="cardNumber" data-cc-number data-cc-eager-type="payment.creditCardType" name="cardNumber" data-ng-model-options="{ allowInvalid: true }" data-ng-model="payment.creditCardNumber">
<span data-ng-show="paymentForm.cardNumber.$dirty && (paymentForm.cardNumber.$valid === false || paymentForm.cardNumber.$valid === true)" class="input-message-validate">
<span data-ng-messages="paymentForm.cardNumber.$error" data-ng-show="paymentForm.cardNumber.$valid === false">
    <span data-ng-message="ccNumber">Bad credit card #</span>
</span>
<i class="icon-tick" data-ng-show="paymentForm.cardNumber.$valid === true"></i>
</span>
```

The ngModelController is updated but the value in the view doesn't kick in until after the first time the user has entered a valid cc number.  This is happening even with allowInvalid the model options.

**Comment by bendrucker** [comment] 2015-02-19 14:48
I can't reproduce this either. Entering `4242` into the card number results in `ng-dirty` being applied to both the input and the form. Both of those are set when a view value update is committed. 

Any ideas on why all these weird issues are popping up for you?

**Closed by bendrucker** 2015-02-19 14:48 UTC

**Comment by owlyowl** [comment] 2015-02-19 22:25
In the example above paymentForm.cardNumber.$dirty never gets set to true if you start typing?
